# Generated by Django 5.2 on 2025-12-03 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot')], default='cold', max_length=10)),
                ('intent_score', models.FloatField(db_index=True, default=0.0, help_text='0-100 score computed by Intent Engine')),
                ('last_scored_at', models.DateTimeField(blank=True, null=True)),
                ('is_enriched', models.BooleanField(default=False)),
                ('enrichment_summary', models.TextField(blank=True)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-intent_score', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProspectEnrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(help_text='e.g. crunchbase, careers_page, news_scraper', max_length=100)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('enriched_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichments', to='prospects.prospect')),
            ],
            options={
                'ordering': ['-enriched_at'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal_type', models.CharField(choices=[('engagement', 'Engagement'), ('hiring', 'Hiring'), ('funding', 'Funding'), ('news', 'News Mention'), ('technical', 'Tech Stack'), ('other', 'Other')], max_length=30)),
                ('score', models.FloatField(help_text='Signal strength contribution (positive/negative)')),
                ('absolute_score', models.FloatField(blank=True, help_text='Absolute intent score after applying this signal (0-100)', null=True)),
                ('reason', models.TextField(blank=True)),
                ('source', models.CharField(help_text='Which integration/check created this signal', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='prospects.prospect')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
